export enum OrderStatus {
  ORDERED = "ORDERED",
  ACCEPTED = "ACCEPTED",
  PREPARING = "PREPARING",
  READY = "READY",
  ON_THE_WAY = "ON_THE_WAY",
  DELIVERED = "DELIVERED",
  CANCELED = "CANCELED",
}

export enum BusinessRequestStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  CANCELED = "CANCELED",
}

export enum OSClass {
  USER = "USER",
  BUSINESS = "BUSINESS",
  PRODUCT = "PRODUCT",
}

export enum OSReviewType {
  ITEM_BY_CUSTOMER = "ITEM_BY_CUSTOMER",
  BUSINESS_BY_CUSTOMER = "BUSINESS_BY_CUSTOMER",
  ORDER_BY_CUSTOMER = "ORDER_BY_CUSTOMER",
  DELIVERY_BY_CUSTOMER = "DELIVERY_BY_CUSTOMER",
  CUSTOMER_BY_BUSINESS = "CUSTOMER_BY_BUSINESS",
  CUSTOMER_BY_DELIVERY = "CUSTOMER_BY_DELIVERY",
}

export enum OSAPOnSpotHomeHODFilter {
  ONLY_HOD_BUSINESS = "ONLY_HOD_BUSINESS",
  OPEN_ALL_BUSINESS = "OPEN_ALL_BUSINESS",
}
